---
- name: Configure Grafana datasource
  ansible.builtin.template:
    src: datasources.yml.j2
    dest: "{{ grafana_provisioning }}/datasources/prometheus.yml"
    owner: root
    group: grafana
    mode: "0640"
  notify: Restart Grafana