---
docker_edition: "ce"
docker_package_state: "present"

docker_group: "docker"
docker_user: "{{ ansible_user }}"

docker_daemon_options:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"

docker_compose_version: "v2.29.7"
docker_compose_plugin_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ ansible_architecture }}"