ansible_user: ansible

prometheus_port: 9090
alertmanager_port: 9093
node_exporter_port: 9100
grafana_port: 3000
elastic_http_port: 9200
elastic_network_host: "0.0.0.0"

kibana_port: 5601
kibana_host: "0.0.0.0"
kibana_elasticsearch_hosts:
  - "http://localhost:9200"

wp_password: "XzZcul$%u6tyw5^4rE"