{
 "title": "Node / Fleet Overview",
 "description": "Nodes summary",
 "tags": [
  "prometheus",
  "grafana-agent",
  "node-exporter",
  "linux-node-integration"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info{sysname!=\"Darwin\", job=\"node-exporter\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\", job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Linux Nodes Overview",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_os_info{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_uname_info{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "time() - node_boot_time_seconds{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "avg by (instance) (node_load1{job=~\"$job\",instance=~\"$instance\"})"
    },
    {
     "expr": "avg by (instance) (node_load5{job=~\"$job\",instance=~\"$instance\"})"
    },
    {
     "expr": "avg by (instance) (node_load15{job=~\"$job\",instance=~\"$instance\"})"
    },
    {
     "expr": "count by (instance) (node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})"
    },
    {
     "expr": "(((count by (instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))\n"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"})\n* 100\n)\n"
    },
    {
     "expr": "node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\", mountpoint=\"/\",fstype!=\"rootfs\"}"
    },
    {
     "expr": "100-(max by (instance) (node_filesystem_avail_bytes{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint=\"/\"})\n/\nmax by (instance) (node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint=\"/\"}) * 100)\n"
    },
    {
     "expr": "count by (instance) (max_over_time(ALERTS{job=~\"$job\",instance=~\"$instance\", alertstate=\"firing\", severity=\"critical\"}[1m])) * group by (instance) (node_uname_info{job=~\"$job\",instance=~\"$instance\"})"
    },
    {
     "expr": "count by (instance) (max_over_time(ALERTS{job=~\"$job\",instance=~\"$instance\", alertstate=\"firing\", severity=\"warning\"}[1m])) * group by (instance) (node_uname_info{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, (((count by (instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))\n)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg((((count by (instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, 100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"})\n* 100\n)\n)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"})\n* 100\n)\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Disks I/O",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, rate(node_disk_io_time_seconds_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Disks Space Usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, sort_desc(1 -\n  (\n  max by (job, instance, fstype, device, mountpoint) (node_filesystem_avail_bytes{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n  /\n  max by (job, instance, fstype, device, mountpoint) (node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n  ) != 0\n)\n)",
     "legendFormat": "{{instance}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Errors and Dropped Packets",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, irate(node_network_receive_errs_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) + irate(node_network_transmit_errs_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) + irate(node_network_receive_drop_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) + irate(node_network_transmit_drop_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) > 0.5",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  }
 ]
}