---
- name: Create Alertmanager directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
    mode: "0755"
  loop:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_data_dir }}"
