---
- name: Create node_exporter group
  ansible.builtin.group:
    name: "{{ node_exporter_user }}"
    system: true

- name: Create node_exporter user 
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false