---
# - name: Check if Prometheus existed
#   ansible.builtin.stat:
#     path: "{{ prometheus_bin_dir }}/prometheus"
#   register: prometheus_binary

- name: Copy Prometheus tarball
  ansible.builtin.copy:
    src: "{{ prometheus_archive }}"
    dest: "/tmp/{{ prometheus_archive }}"
    mode: "0644"
  # when: not prometheus_binary.stat.exists

- name: Extract Prometheus archive
  ansible.builtin.unarchive:
    src: "/tmp/{{ prometheus_archive }}"
    dest: /tmp
    remote_src: true

- name: Install Prometheus binaries
  ansible.builtin.copy:
    src: "{{ prometheus_extract_dir }}/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  loop:
    - prometheus
    - promtool

# - name: Remove Prometheus tarball
#   ansible.builtin.file:
#     path: "/tmp/{{ prometheus_archive }}"
#     state: absent