---
grafana_repo_url: https://apt.grafana.com
grafana_channel: stable

grafana_gpg_key_url: https://apt.grafana.com/gpg.key

grafana_admin_user: admin

grafana_package: grafana
grafana_service: grafana-server

grafana_provisioning: /etc/grafana/provisioning