---
- name: Update apt cache
  apt:
    name:
      - curl
      - wget
      - git
      - unzip
      - vim
      - software-properties-common
      - apt-transport-https
      - gnupg
      - ca-certificates
    state: present
    update_cache: true
    cache_valid_time: 86400

- name: Set needrestart to non-interactive mode
  ansible.builtin.copy:
    dest: /etc/needrestart/needrestart.conf
    content: |
      $nrconf{restart} = 'a';
    owner: root
    mode: "0644"