---
- name: Configure prerequisite all nodes
  hosts: all
  become: true

  roles:
    - role: common
      tags:
        - common

- name: Configure Control Node
  hosts: controls
  become: true

  roles:
    - role: prometheus
      tags:
        - prometheus

    - role: grafana
      tags:
        - grafana

    - role: elastic_stack
      tags:
        - elastic_stack

    - role: kibana
      tags:
        - kibana

    - role: alert_manager
      tags:
        - alert_manager

- name: Configure Target Nodes
  hosts: nodes
  become: true

  roles:
    - role: node_exporter
      tags:
        - node_exporter

    - role: elastic_agent
      tags:
        - elastic_agent

    - role: docker
      tags:
        - docker

    - role: cadvisor
      tags:
        - cadvisor

    - role: web
      tags:
        - web